# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Davor Physical Therapy and Rehabilitation
email: davor@davor.pt
description: Get on the path to recovery and excellence
baseurl: "" # the subpath of your site, e.g. /blog
url: http://davor.pt # the base hostname & protocol for your site
twitterUrl: 
facebookUrl: 
instagramUrl: 
googleMapsApiKey: 
# Google services
google_analytics: 

# Build settings
markdown: kramdown
